runtime: nodejs14
service: gatsby

handlers:
- url: /gatbsy
  static_files: public/index.html
  upload: public/index.html
- url: /gatsby/
  static_files: public/index.html
  upload: public/index.html
- url: /gatsby/(.*)
  static_files: public/\1/index.html
  upload: public/(.*)

